name: Deploy to Railway

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Railway CLI
        run: npm install -g railway

      - name: Autenticarse en Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy a Railway
        run: railway up
